config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :forms, only: [:new, :create, :index, :show, :destroy] do
    get "submitted", on: :collection
  end
root to: "forms#new"
  resources :forms

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/form.rb
class Form < ActiveRecord::Base
    enum gender: [ :male, :female ]
    enum grade: ["9th", "10th", "11th", "12th" ]
    enum race: ["African-American", "Asian","Caucasian", "Hispanic", "Native American","Other"]
    enum tshirt_size: ["S", "M", "L", "XL", "2XL", "3XL"] 
    enum household_income: ["Less than $11,880", "$11,881 - $16,020", "$16,021 - $20,160", "$20,161 - $24,440", "$24,441 - $28,440", "28,441 - $32,580", "$32,581 - $36,730", "$36,731 - $40,890", "More than $40,891", ]
    enum healthy_la_provider: ["Aetna Better Health of Louisiana", "Amerigroup Louisiana, Inc.", "AmeriHealth Caritas Louisiana, Inc.", "Louisiana Healthcare Connections", "United Healthcare Community Plan"]

    validates :first_name, presence: true
    validates :middle_name, presence: true
    validates :last_name, presence: true
    validates :address, presence: true
    validates :city, presence: true
    validates :state, presence: true
    validates :zipcode, presence: true
    validates :cellphone_number, presence: true
    validates :date_of_birth, presence: true 
    validates :social_security_number, presence: true
    validates :gender, presence: true
    validates :email_addresses, presence: true, format: { with: /\A\S+@\S+\z/ }
    validates :school, presence: true
    validates :grade, presence: true
    validates :race, presence: true 
    validates :tshirt_size, presence: true 
    validates :doctor_name, presence: true
    validates :doctor_workphone, presence: true
    validates :guardian1_contact_name, presence: true
    validates :guardian1_contact_employment, presence: true
    validates :guardian1_contact_workphone, presence: true 
    validates :guardian1_contact_homephone, presence: true
    validates :guardian1_contact_cellphone, presence: true
    validates :guardian1_contact_email, presence: true 
    validates :emergency_contact_name, presence: true
    validates :emergency_contact_relationship, presence: true
    validates :emergency_contact_workphone, presence: true
    validates :emergency_contact_cellphone, presence: true
    validates :household_adults, presence: true
    validates :household_children, presence: true
    validates :household_income, presence: true
    validates :essay_question, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
    forms_path
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:new, :create, :submitted]

  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.order(created_at: :asc)
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
  end

  def submitted
  end
  
  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to submitted_forms_path, notice: 'Form was successfully created.' }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to @form, notice: 'Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:form).permit(
        :first_name,
        :middle_name,
        :last_name,
        :address,
        :city,
        :state,
        :zipcode,
        :cellphone_number,
        :date_of_birth,
        :social_security_number,
        :gender,
        :email_addresses,
        :school,
        :grade,
        :race,
        :indiviual_graduation_plan, 
        :special_education_services, 
        :free_lunch, 
        :parent_in_prison, 
        :ESL_services, 
        :tshirt_size, 
        :doctor_name, 
        :doctor_workphone, 
        :medical_restrictions,
        :medical_restrictions_explained,
        :medications,
        :medications_explained,
        :allergies,
        :allergies_explained,
        :guardian1_contact_name,
        :guardian1_contact_employment,
        :guardian1_contact_workphone,
        :guardian1_contact_homephone,
        :guardian1_contact_cellphone, 
        :guardian1_contact_email, 
        :guardian2_contact_name, 
        :guardian2_contact_employment, 
        :guardian_contact_workphone, 
        :guardian2_contact_homephone,
        :guardian2_contact_cellphone,
        :guardian2_contact_email,
        :emergency_contact_name,
        :emergency_contact_relationship, 
        :emergency_contact_workphone,
        :emergency_contact_cellphone,
        :household_adults,
        :household_children,
        :household_mom,
        :household_dad,
        :household_stepmom,
        :household_stepdad,
        :household_grandparents,
        :household_foster_parent,
        :household_other,
        :household_income,
        :essay_question,
        :healthy_la_qualifcation,
        :healthy_la_provider,
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= form_for(@form) do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% @form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <h2>Scholar's Information</h2>
  </div>

  <div class="field">
    <%= f.label :first_name, "First Name" %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name, "Middle Initial " %><br>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :last_name, "Last Name"%><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :cellphone_number, "Cellphone Number" %><br>
    <%= f.telephone_field :cellphone_number %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth, "Date of Birth" %><br>
    <%= f.date_field :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :social_security_number, "Social Security Number" %><br>
    <%= f.password_field :social_security_number %>
  </div>
  
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.label :gender, "Male", value:  "male" %>
    <%= f.radio_button :gender, "male" %>
    <%= f.label :gender, "Female", value:  "female" %>
    <%= f.radio_button :gender, "female" %>
  </div>
  
  <div class="field">
    <%= f.label :email_addresses, "Email Address" %><br>
    <%= f.email_field :email_addresses %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :grade %><br>
    <%= f.select :grade, Form.grades.keys.to_a %>
  </div>
  <div class="field">
    <%= f.label :race %><br>
    <%= f.select :race, Form.races.keys.to_a %>
  </div>
  <div class="field">
    <%= f.label :indiviual_graduation_plan %><br>
    <%= f.check_box :indiviual_graduation_plan %>
  </div>
  <div class="field">
    <%= f.label :special_education_services %><br>
    <%= f.check_box :special_education_services %>
  </div>
  <div class="field">
    <%= f.label :free_lunch %><br>
    <%= f.check_box :free_lunch %>
  </div>
  <div class="field">
    <%= f.label :parent_in_prison %><br>
    <%= f.check_box :parent_in_prison %>
  </div>
  <div class="field">
    <%= f.label :ESL_services %><br>
    <%= f.check_box :ESL_services %>
  </div>
  <div class="field">
    <%= f.label :tshirt_size %><br>
    <%= f.select :tshirt_size, Form.tshirt_sizes.keys.to_a %>
  </div>
  
  <div class="feild">
    <%= f.label :healthy_la_qualifcation %><br>
    <%= f.check_box :healthy_la_qualifcation %>
  </div>
  
  <div class="field">
    <%= f.label :healthy_la_provider %><br>
    <%= f.select :healthy_la_provider, Form.healthy_la_providers.keys.to_a, include_blank: true%>
  </div>
  
  
  <div class="form-section">
    <h2>Household Information</h2>
    
    <div class="field">
      <%= f.label :household_adults, "Number of adults in household"%><br>
      <%= f.number_field :household_adults %>
      </div>
    
    <div class="field">
      <%= f.label :household_children, "Number of children in household"%><br>
      <%= f.number_field :household_children %>
    </div>
    
    <div class="field">
      <%= f.label :household_mom %><br>
      <%= f.check_box :household_mom %>
    </div>
    
    <div class="field">
      <%= f.label :household_dad %> <br>
      <%= f.check_box :household_dad %>
    </div>
    
    <div class="field">
      <%= f.label :household_stepmom %><br>
      <%= f.check_box :household_stepmom %>
    </div>
    
    <div class="field">
      <%= f.label :household_stepdad %><br>
      <%= f.check_box :household_stepdad %>
    </div>
    
    <div class="field">
      <%= f.label :household_grandparents %><br>
      <%= f.check_box :household_grandparents %>
    </div>
    
    <div class="field">
      <%= f.label :household_foster_parent %><br>
      <%= f.check_box :household_foster_parent %>
    </div>
    
    <div class="field">
      <%= f.label :household_other %><br>
      <%= f.text_field :household_other %>
    </div>
    
    <div class="field">
      <%= f.label :household_income %><br>
      <%= f.select :household_income, Form.household_incomes.keys.to_a, include_blank: true %>
    </div>

  </div>
  
  <div class="form-section">
    <h2>Medical Information</h2>
    
    <div class="field">
      <%= f.label :doctor_name %><br>
      <%= f.text_field :doctor_name %>
    </div>
    <div class="field">
      <%= f.label :doctor_workphone %><br>
      <%= f.telephone_field :doctor_workphone %>
    </div>
    <div class="field">
      <%= f.label :medical_restrictions %><br>
      <%= f.check_box :medical_restrictions %>
    </div>
    <div class="field">
      <%= f.label :medical_restrictions_explained %><br>
      <%= f.text_area :medical_restrictions_explained %>
    </div>
    <div class="field">
      <%= f.label :medications %><br>
      <%= f.check_box :medications %>
    </div>
    <div class="field">
      <%= f.label :medications_explained %><br>
      <%= f.text_area :medications_explained %>
    </div>
    <div class="field">
      <%= f.label :allergies %><br>
      <%= f.check_box :allergies %>
    </div>
    <div class="field">
      <%= f.label :allergies_explained %><br>
      <%= f.text_area :allergies_explained %>
    </div>
  </div>
  
  <div class="form-section">
    <h2>Contact Information</h2>
    <div class="field">
      <%= f.label :guardian1_contact_name, "Guardian's Contact Name" %><br>
      <%= f.text_field :guardian1_contact_name %>
    </div>
    <div class="field">
      <%= f.label :guardian1_contact_employment, "Guardian's Employment" %><br>
      <%= f.text_field :guardian1_contact_employment %>
    </div>
    <div class="field">
      <%= f.label :guardian1_contact_workphone, "Guardian's Workphone Number" %><br>
      <%= f.telephone_field :guardian1_contact_workphone %>
    </div>
    <div class="field">
      <%= f.label :guardian1_contact_homephone, "Guardian's Contact Homephone Number" %><br>
      <%= f.telephone_field :guardian1_contact_homephone %>
    </div>
    <div class="field">
      <%= f.label :guardian1_contact_cellphone, "Guardian's Cellphone Number" %><br>
      <%= f.telephone_field :guardian1_contact_cellphone %>
    </div>
    <div class="field">
      <%= f.label :guardian1_contact_email, "Guardian's Email" %><br>
      <%= f.email_field :guardian1_contact_email %>
    </div>
    <div class="field">
      <%= f.label :emergency_contact_name, "Emergency Contact's Name" %><br>
      <%= f.text_field :emergency_contact_name %>
    </div>
    <div class="field">
      <%= f.label :emergency_contact_relationship, "Emergency Contact's Relationship" %><br>
      <%= f.text_field :emergency_contact_relationship %>
    </div>
    <div class="field">
      <%= f.label :emergency_contact_workphone, "Emergency Contact's Workphone" %><br>
      <%= f.telephone_field :emergency_contact_workphone %>
    </div>
    <div class="field">
      <%= f.label :emergency_contact_cellphone, "Emergency Contact's Cellphone" %><br>
      <%= f.telephone_field :emergency_contact_cellphone %>
    </div>
  </div>

<div class="form-section">
  <h2>Essay</h2>
  <p>
    Choose one of the writing prompts below and respond to the best of your ability.
    <ol>
      <li>When you look in the mirror, what do you see? Describe what you see, how you feel about your own reflection, and what it prompts you to do.</li>
      <li>Write about the most valuable lesson you ever learned. What made it so useful for you?</li>
      <li>Who is a person you admire? How would they describe you?</li>
    </ol>
    <div class="field">
      <%= f.text_area :essay_question %>
    </div>
  </p>
  
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<h1>Editing Form</h1>

<%= render 'form' %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forms</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Submitted On</th>
  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= form.first_name %></td>
        <td><%= form.last_name %></td>
        <td><%= form.created_at.strftime "%b %e, %Y @ %l:%M %p" %></td>
        <td><%= link_to 'Show', form %></td>
        <td><%= link_to 'Edit', edit_form_path(form) %></td>
        <td><%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Form', new_form_path %>

app/views/forms/new.html.erb
<h1>New Form</h1>

<%= render 'form' %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>Press Ctrl+P to Print</p>

<p>
  <strong>Submitted On</strong>
  <%= @form.created_at.strftime "%b %e, %Y @ %l:%M %p" %>
</p>

<p>
  <strong>First name:</strong>
  <%= @form.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @form.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @form.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @form.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @form.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @form.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @form.zipcode %>
</p>

<p>
  <strong>Cellphone number:</strong>
  <%= @form.cellphone_number %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @form.date_of_birth %>
</p>

<p>
  <strong>Social security number:</strong>
  <%= @form.social_security_number %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @form.gender %>
</p>

<p>
  <strong>Email addresses:</strong>
  <%= @form.email_addresses %>
</p>

<p>
  <strong>School:</strong>
  <%= @form.school %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @form.grade %>
</p>

<p>
  <strong>Race:</strong>
  <%= @form.race %>
</p>

<p>
  <strong>Indiviual graduation plan:</strong>
  <%= @form.indiviual_graduation_plan %>
</p>

<p>
  <strong>Special education services:</strong>
  <%= @form.special_education_services %>
</p>

<p>
  <strong>Free lunch:</strong>
  <%= @form.free_lunch %>
</p>

<p>
  <strong>Parent in prison:</strong>
  <%= @form.parent_in_prison %>
</p>

<p>
  <strong>Esl services:</strong>
  <%= @form.ESL_services %>
</p>

<p>
  <strong>Tshirt size:</strong>
  <%= @form.tshirt_size %>
</p>

<p>
  <strong> Healthy la eligibility</strong>
  <%= @form.healthy_la_qualifcation %>
</p>

<p>
  <strong>Healthy la provider</strong>
  <%= @form.healthy_la_provider %>
</p>

<p>
  <strong>Household adults:</strong>
  <%= @form.household_adults %>
</p>

<p>
  <strong>Household children:</strong>
  <%= @form.household_children %>
</p>

<p>
  <strong>Household mom:</strong>
  <%= @form.household_mom %>
</p>

<p>
  <strong>Household dad:</strong>
  <%= @form.household_dad %>
</p>

<p>
  <strong>Household stepmom:</strong>
  <%= @form.household_stepmom %>
</p>

<p>
  <strong>Household stepdad:</strong>
  <%= @form.household_stepdad %>
</p

><p>
  <strong>Household grandparents:</strong>
  <%= @form.household_grandparents %>
</p><p>
  <strong>Household foster parent:</strong>
  <%= @form.household_foster_parent %>
</p>

<p>
  <strong>Household other:</strong>
  <%= @form.household_other %>
</p>

<p>
  <strong>Household income:</strong>
  <%= @form.household_income %>
</p>

<p>
  <strong>Doctor name:</strong>
  <%= @form.doctor_name %>
</p>

<p>
  <strong>Doctor workphone:</strong>
  <%= @form.doctor_workphone %>
</p>

<p>
  <strong>Medical restrictions:</strong>
  <%= @form.medical_restrictions %>
</p>

<p>
  <strong>Medical restrictions explained:</strong>
  <%= @form.medical_restrictions_explained %>
</p>

<p>
  <strong>Medications:</strong>
  <%= @form.medications %>
</p>

<p>
  <strong>Medications explained:</strong>
  <%= @form.medications_explained %>
</p>

<p>
  <strong>Allergies:</strong>
  <%= @form.allergies %>
</p>

<p>
  <strong>Allergies explained:</strong>
  <%= @form.allergies_explained %>
</p>

<p>
  <strong>Guardian1 contact name:</strong>
  <%= @form.guardian1_contact_name %>
</p>

<p>
  <strong>Guardian1 contact employment:</strong>
  <%= @form.guardian1_contact_employment %>
</p>

<p>
  <strong>Guardian1 contact workphone:</strong>
  <%= @form.guardian1_contact_workphone %>
</p>

<p>
  <strong>Guardian1 contact homephone:</strong>
  <%= @form.guardian1_contact_homephone %>
</p>

<p>
  <strong>Guardian1 contact cellphone:</strong>
  <%= @form.guardian1_contact_cellphone %>
</p>

<p>
  <strong>Guardian1 contact email:</strong>
  <%= @form.guardian1_contact_email %>
</p>

<p>
  <strong>Emergency contact name:</strong>
  <%= @form.emergency_contact_name %>
</p>

<p>
  <strong>Emergency contact relationship:</strong>
  <%= @form.emergency_contact_relationship %>
</p>

<p>
  <strong>Emergency contact workphone:</strong>
  <%= @form.emergency_contact_workphone %>
</p>

<p>
  <strong>Emergency contact cellphone:</strong>
  <%= @form.emergency_contact_cellphone %>
</p>

<p>
  <strong>Essay question:</strong>
  <%= @form.essay_question %>
</p>

<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>

app/views/forms/submitted.html.erb
<div class="submitted-box">
  <h1>Submitted successfully</h1>
  
  <p>
    <em>Your application has been submitted and is being processed!</em>
  </p>
  
  <p>
    Do you have another child interested in joining us this summer?
    Submit another application <%= link_to "here", new_form_path %>.
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">
    <% if admin_signed_in? %>
      <p>
        Sign in as <%= current_admin.email %>
        <%= link_to "Sign out", destroy_admin_session_path, method: :delete %>
      </p>
    <% else %>
      <p>
        <%= link_to "Admin sign in", new_admin_session_path %>
      </p>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>